version: '3'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg9.6
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=automacion
